services:
  php-apache-slim:
    build: .
    ports:
      - "8180:80"  # Używamy portu 8180 zamiast 8080
    volumes:
      - .:/var/www/html
      - ./chunks:/chunks  # Montowanie katalogu ./chunks na hosta do /chunks w kontenerze
      - ./output:/output  # Montowanie katalogu output jako woluminu
      - ./logs:/var/log/php_errors
    depends_on:
      - db-slim

  db-slim:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    volumes:
      - pgdata-slim:/var/lib/postgresql/data

  pgadmin-slim:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=test123
    ports:
      - "8181:80"  # Używamy portu 8181 zamiast 8081
    depends_on:
      - db-slim
    volumes:
      - pgadmin-data-slim:/var/lib/pgadmin

volumes:
  pgdata-slim:
  pgadmin-data-slim: